import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const iranSans = localFont({ src: "./IRANSans.woff2" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='fa' dir='rtl'>
			<body className={`${iranSans.className} h-screen w-screen overflow-x-hidden overflow-y-auto`}>
				{children}
			</body>
		</html>
	);
}
